# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np



In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_dimensional_array = np.array([1, 2, 3, 4, 5])


# Create a 2-dimensional NumPy array using np.array()
two_dimensional_array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])


# Create a 3-dimensional Numpy array using np.array()
three_dimensional_array = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]]])



Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(one_dimensional_array.shape)
print(one_dimensional_array.ndim)
print(one_dimensional_array.dtype)
print(one_dimensional_array.size)
print(type(one_dimensional_array))



(5,)
1
int32
5
<class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
print(two_dimensional_array.shape)
print(two_dimensional_array.ndim)
print(two_dimensional_array.dtype)
print(two_dimensional_array.size)
print(type(two_dimensional_array))



(2, 5)
2
int32
10
<class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array
print(three_dimensional_array.shape)
print(three_dimensional_array.ndim)
print(three_dimensional_array.dtype)
print(three_dimensional_array.size)
print(type(three_dimensional_array))



(2, 2, 5)
3
int32
20
<class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(two_dimensional_array)
print(df)


   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [7]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))
ones_array


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7,2,3))
zeros_array


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7,2))
random_array




array([[4, 8],
       [0, 1],
       [4, 6],
       [4, 8],
       [0, 6],
       [9, 8],
       [3, 3]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2 = np.random.random((3,5))
random_array_2



array([[0.5455533 , 0.4796089 , 0.05749542, 0.88798096, 0.04656645],
       [0.15232065, 0.10753534, 0.79090416, 0.30816221, 0.54096692],
       [0.35876806, 0.48445249, 0.67401747, 0.31954073, 0.15597565]])

In [13]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 = np.random.randint(0, 10, size=(4,6))
random_array


array([[4, 8],
       [0, 1],
       [4, 6],
       [4, 8],
       [0, 6],
       [9, 8],
       [3, 3]])

Run the cell above again, what happens?
### the numbers are the same 
Are the numbers in the array different or the same? Why do think this is?
### same , as the random seed is a fixed number now of value 42

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4 = np.random.randint(1, 10, size=(3,7))
random_array_4



# Find the unique numbers in the array you just created
print(np.unique(random_array_4))



[1 2 3 4 5 7 9]


In [15]:
# Find the 0'th index of the latest array you created
print(random_array_4[0])



[9 1 3 7 4 9 3]


In [16]:
# Get the first 2 rows of latest array you created
print(random_array_4[:2])



[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]]


In [17]:
# Get the first 2 values of the first 2 rows of the latest array
print(random_array_4[:2, :2])



[[9 1]
 [5 3]]


In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_5 = np.random.randint(0, 10, size=(3,5))

ones_array_2 = np.ones((3,5))
ones_array_2



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Add the two arrays together
print(random_array_5 + ones_array_2)



[[ 7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.]
 [ 6. 10.  4.  6.  2.]]


In [20]:
# Create another array of ones of shape (5, 3)
ones_array_3 = np.ones((5,3))



In [21]:
# Try add the array of ones and the other most recent array together
print(random_array_5 + ones_array_3)



ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

### How would you fix it? reshaping 

In [22]:
# Create another array of ones of shape (3, 5)
ones_array_4 = np.ones((3,5))


In [23]:
# Subtract the new array of ones from the other most recent array
print(random_array_5 - ones_array_4)



[[ 5.  6.  1. -1.  2.]
 [ 0.  6.  2.  0.  4.]
 [ 4.  8.  2.  4.  0.]]


In [24]:
# Multiply the ones array with the latest array
print(random_array_5 * ones_array_4)



[[6. 7. 2. 0. 3.]
 [1. 7. 3. 1. 5.]
 [5. 9. 3. 5. 1.]]


In [25]:
# Take the latest array to the power of 2 using '**'
print(random_array_5 ** 2)



[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]


In [26]:
# Do the same thing with np.square()
print(np.square(random_array_5))


[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]


In [27]:
# Find the mean of the latest array using np.mean()
print(np.mean(random_array_5))


3.8666666666666667


In [28]:
# Find the maximum of the latest array using np.max()
print(np.max(random_array_5))



9


In [29]:
# Find the minimum of the latest array using np.min()
print(np.min(random_array_5))


0


In [30]:
# Find the standard deviation of the latest array
print(np.std(random_array_5))


2.578543947441829


In [31]:
# Find the variance of the latest array
print(np.var(random_array_5))


6.648888888888889


In [32]:
# Reshape the latest array to (3, 5, 1)
print(random_array_5.reshape(3,5,1))


[[[6]
  [7]
  [2]
  [0]
  [3]]

 [[1]
  [7]
  [3]
  [1]
  [5]]

 [[5]
  [9]
  [3]
  [5]
  [1]]]


In [33]:
# Transpose the latest array
print(random_array_5.T)


[[6 1 5]
 [7 7 9]
 [2 3 3]
 [0 1 5]
 [3 5 1]]


What does the transpose do?

In [34]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_6 = np.random.randint(0, 10, size=(3,3))
random_array_7 = np.random.randint(0, 10, size=(3,2))



In [35]:
# Perform a dot product on the two newest arrays you created
print(np.dot(random_array_6, random_array_7))



[[ 88 117]
 [100 123]
 [ 89 127]]


In [36]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_8 = np.random.randint(0, 10, size=(4,3))
random_array_9 = np.random.randint(0, 10, size=(4,3))
random_array_8
random_array_9



array([[2, 0, 4],
       [9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [37]:
# Perform a dot product on the two newest arrays you created
print(np.dot(random_array_8, random_array_9))


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it? ## by transpose

In [38]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
print(np.dot(random_array_8, random_array_9.T))



[[ 24 102  96   8]
 [ 16 114 106  63]
 [ 22 123 114  56]
 [  8  60  58   7]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [39]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_10 = np.random.randint(0, 10, size=(3,5))
random_array_11 = np.random.randint(0, 10, size=(3,5))



In [40]:
# Compare the two arrays with '>'
print(random_array_10 > random_array_11)



[[False False False False False]
 [ True False  True False False]
 [False False False  True  True]]


What happens when you compare the arrays with `>`?

In [41]:
# Compare the two arrays with '>='
print(random_array_10 >= random_array_11)


[[ True  True False False False]
 [ True False  True False False]
 [ True False False  True  True]]


In [42]:
# Find which elements of the first array are greater than 7
print(random_array_10 > 7)



[[False False False False False]
 [False False False False False]
 [False False False False  True]]


In [43]:
# Which parts of each array are equal? (try using '==')
print(random_array_10 == random_array_11)


[[ True  True False False False]
 [False False False False False]
 [ True False False False False]]


In [44]:
# Sort one of the arrays you just created in ascending order
print(np.sort(random_array_10))


[[2 4 6 6 7]
 [0 2 2 5 7]
 [0 2 4 4 9]]


In [45]:
# Sort the indexes of one of the arrays you just created
print(np.argsort(random_array_10))


[[4 3 0 1 2]
 [3 2 4 1 0]
 [2 1 0 3 4]]


In [46]:
# Find the index with the maximum value in one of the arrays you've created
print(np.argmax(random_array_10))


14


In [47]:
# Find the index with the minimum value in one of the arrays you've created
print(np.argmin(random_array_10))


8


In [48]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(np.argmax(random_array_10, axis=1))


[2 0 4]


In [49]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(np.argmin(random_array_10, axis=0))


[2 2 2 1 0]


In [50]:
# Create an array of normally distributed random numbers
# Set the mean and standard deviation
mean = 0
std_dev = 1
array_size = 10

random_numbers = np.random.normal(mean, std_dev, array_size)
random_numbers


array([-0.8084936 , -0.50175704,  0.91540212,  0.32875111, -0.5297602 ,
        0.51326743,  0.09707755,  0.96864499, -0.70205309, -0.32766215])

In [51]:
# Create an array with 10 evenly spaced numbers between 1 and 100
print(np.linspace(1, 100, 10))


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.